<?php
// reminder.php
require_once 'config.php';

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'add_reminder') {
    $vehicle_id = $_POST['vehicle_id'] ?? '';
    $tanggal = $_POST['tanggal'] ?? '';
    $reminder_type = $_POST['reminder_type'] ?? '';
    $vehicle_type = $_POST['vehicle_type'] ?? '';

    // Validation
    $errors = [];
    if (empty($vehicle_id)) $errors[] = 'Pilih kendaraan terlebih dahulu.';
    if (empty($tanggal)) $errors[] = 'Tanggal jatuh tempo harus diisi.';
    if (empty($reminder_type)) $errors[] = 'Pilih jenis pengingat.';

    if (empty($errors)) {
        // Here you would insert into database
        // For now, just add to sample data
        $newReminder = [
            'id' => count($reminders) + 1,
            'vehicle_id' => (int)$vehicle_id,
            'tanggal' => $tanggal,
            'reminder_type' => $reminder_type,
            'vehicle' => array_filter($vehicles, function ($v) use ($vehicle_id) {
                return $v['id'] == $vehicle_id;
            })[0] ?? null
        ];
        $reminders[] = $newReminder;
        $_SESSION['success'] = 'Pengingat berhasil disimpan!';

        // Redirect to prevent form resubmission
        header('Location: reminder.php');
        exit;
    } else {
        $_SESSION['errors'] = $errors;
    }
}

$success = $_SESSION['success'] ?? null;
$errors = $_SESSION['errors'] ?? [];
unset($_SESSION['success'], $_SESSION['errors']);

$pageTitle = 'Pengingat';
include 'includes/header.php';
?>

<!-- Main Content -->
<main class="pt-24 pb-12 bg-gray-50">
    <div class="max-w-7xl mx-auto pt-10">
        <div class="flex flex-col lg:flex-row gap-8">

            <!-- LEFT SIDE - CALENDAR -->
            <div class="flex-1">
                <!-- Month Header -->
                <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8 p-4">
                    <div class="flex items-center gap-4">
                        <button id="prevMonth" class="w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center hover:bg-primary-dark transition-colors">
                            <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                <path d="M15 18l-6-6 6-6"></path>
                            </svg>
                        </button>
                        <h2 id="currentMonthYear" class="text-xl font-bold text-gray-800 min-w-[200px] text-center"></h2>
                        <button id="nextMonth" class="w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center hover:bg-primary-dark transition-colors">
                            <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                <path d="M9 18l6-6-6-6"></path>
                            </svg>
                        </button>
                    </div>

                    <div class="relative w-full sm:w-80">
                        <svg class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                            <circle cx="11" cy="11" r="8"></circle>
                            <path d="M21 21l-4.35-4.35"></path>
                        </svg>
                        <input
                            type="text"
                            placeholder="Cari kendaraan..."
                            id="searchVehicle"
                            class="w-full pl-10 pr-4 py-2.5 rounded-lg border border-gray-200 bg-gray-50 text-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary" />
                    </div>
                </div>

                <!-- Calendar Card -->
                <div class="bg-white rounded-2xl border border-gray-100 overflow-hidden shadow-sm">
                    <!-- Calendar Header -->
                    <div class="grid grid-cols-7 bg-gray-50/80 border-b border-gray-100">
                        <?php foreach (['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'] as $day): ?>
                            <div class="py-3 text-center text-sm font-semibold text-gray-600 border-r border-gray-100 last:border-r-0">
                                <?php echo $day; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <!-- Calendar Grid -->
                    <div id="calendarGrid" class="grid grid-cols-7">
                        <!-- Generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- RIGHT SIDE - FORM -->
            <div class="w-full lg:w-[380px] flex-shrink-0">
                <div class="px-4 pt-4">

                    <!-- Alert Messages -->
                    <?php if ($success): ?>
                        <div class="mb-4 p-3 bg-green-50 border border-green-200 rounded-lg text-green-700 text-sm animate-fadeIn">
                            <?php echo htmlspecialchars($success); ?>
                        </div>
                    <?php endif; ?>

                    <?php if (!empty($errors)): ?>
                        <div class="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm animate-fadeIn">
                            <?php foreach ($errors as $error): ?>
                                <p><?php echo htmlspecialchars($error); ?></p>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>

                    <!-- Action Buttons -->
                    <div class="flex gap-3 mb-6">
                        <button id="btnAddReminder" class="flex-1 bg-primary text-white py-2.5 px-4 rounded-lg text-sm font-medium hover:bg-primary-dark active:scale-95 transition-all">
                            + Tambah
                        </button>
                        <button id="btnCancel" class="flex-1 bg-purple-50 text-primary py-2.5 px-4 rounded-lg text-sm font-medium hover:bg-purple-100 active:scale-95 transition-all flex items-center justify-center gap-1.5">
                            <svg width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                <path d="M18 6L6 18M6 6l12 12"></path>
                            </svg>
                            Batalkan
                        </button>
                    </div>

                    <!-- Form -->
                    <form id="reminderForm" action="reminder.php" method="POST">
                        <input type="hidden" name="action" value="add_reminder">

                        <!-- Vehicle Selection -->
                        <div class="mb-3">
                            <label class="block text-sm font-medium text-gray-700 mb-2">Kendaraan</label>
                            <div class="relative">
                                <select
                                    id="vehicleSelect"
                                    name="vehicle_id"
                                    class="w-full appearance-none px-4 py-3 rounded-lg border border-gray-200 text-sm text-gray-600 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary cursor-pointer"
                                    required>
                                    <option value="">Pilih kendaraan</option>
                                    <?php foreach ($vehicles as $vehicle): ?>
                                        <option
                                            value="<?php echo $vehicle['id']; ?>"
                                            data-plate="<?php echo htmlspecialchars($vehicle['no_polisi']); ?>"
                                            data-type="<?php echo $vehicle['jenis']; ?>"
                                            data-tax-date="<?php echo $vehicle['tanggal_pajak']; ?>">
                                            <?php echo htmlspecialchars($vehicle['no_polisi']); ?> (<?php echo ucfirst($vehicle['jenis']); ?>)
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                                <svg class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                    <path d="M6 9l6 6 6-6"></path>
                                </svg>
                            </div>
                            <?php if (empty($vehicles)): ?>
                                <p class="text-xs text-amber-600 mt-2">Silakan cek pajak dengan NIK terlebih dahulu di halaman Cek Pajak.</p>
                            <?php endif; ?>
                        </div>

                        <!-- Vehicle Type -->
                        <div class="mb-3">
                            <label class="block text-sm font-medium text-gray-700 mb-2">
                                Tipe Kendaraan
                            </label>
                            <div id="vehicleTypeToggle" class="flex gap-2">
                                <button
                                    type="button"
                                    id="btnMotor"
                                    data-type="motor"
                                    class="toggle-btn flex-1 flex items-center justify-center gap-2 py-2.5 px-3 rounded-lg border-2 text-sm font-medium transition-all"
                                    disabled>
                                    <img width="20" height="20" src="https://img.icons8.com/glyph-neue/50/4f46e5/motorcycle.png" alt="motor" />
                                    Motor
                                </button>
                                <button
                                    type="button"
                                    id="btnMobil"
                                    data-type="mobil"
                                    class="toggle-btn flex-1 flex items-center justify-center gap-2 py-2.5 px-3 rounded-lg border-2 text-sm font-medium transition-all"
                                    disabled>
                                    <img width="20" height="20" src="https://img.icons8.com/ios-glyphs/50/4f46e5/car.png" alt="mobil" />
                                    Mobil
                                </button>
                            </div>
                            <input type="hidden" name="vehicle_type" id="vehicleTypeInput" value="">
                        </div>

                        <!-- Tax Due Date -->
                        <div class="mb-3">
                            <label class="block text-sm font-medium text-gray-700 mb-2">Tanggal Jatuh Tempo Pajak</label>
                            <div class="relative">
                                <input
                                    type="text"
                                    id="taxDueDateDisplay"
                                    disabled
                                    readonly
                                    placeholder="Pilih kendaraan terlebih dahulu"
                                    class="w-full px-4 py-3 rounded-lg border border-gray-200 bg-gray-100 text-gray-400 text-sm cursor-not-allowed" />
                                <input type="hidden" name="tanggal" id="taxDueDate" value="">
                                <div class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400/30">
                                    <svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                                        <path d="M16 2v4M8 2v4M3 10h18"></path>
                                    </svg>
                                </div>
                            </div>
                        </div>

                        <!-- Reminder Before Due Date -->
                        <div class="mb-3">
                            <label class="block text-sm font-medium text-gray-700 mb-2">Pengingat Sebelum Jatuh Tempo</label>
                            <div id="reminderDaysToggle" class="flex gap-2">
                                <button type="button" data-days="3" class="reminder-btn flex-1 py-2 px-3 rounded-lg border-2 text-sm font-medium transition-all" disabled>
                                    3 Hari
                                </button>
                                <button type="button" data-days="7" class="reminder-btn flex-1 py-2 px-3 rounded-lg border-2 text-sm font-medium transition-all" disabled>
                                    7 Hari
                                </button>
                                <button type="button" data-days="30" class="reminder-btn flex-1 py-2 px-3 rounded-lg border-2 text-sm font-medium transition-all" disabled>
                                    30 Hari
                                </button>
                            </div>
                            <input type="hidden" name="reminder_type" id="reminderDaysInput" value="">
                        </div>

                        <!-- Mini Calendar -->
                        <div class="mb-5 bg-gray-100 rounded-xl p-3">
                            <div id="miniCalendarGrid" class="grid grid-cols-7 gap-y-1.5 text-center">
                                <!-- Generated by JavaScript -->
                            </div>
                        </div>

                        <!-- Submit Button -->
                        <button type="submit" id="submitReminder" class="w-full bg-primary text-white py-3.5 rounded-lg text-sm font-medium hover:bg-primary-dark active:scale-95 transition-all disabled:opacity-50 disabled:cursor-not-allowed" disabled>
                            Pilih Kendaraan
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

<!-- Event Detail Modal -->
<div id="eventDetailModal" class="fixed inset-0 bg-black/50 z-50 hidden items-center justify-center">
    <div class="bg-white rounded-2xl max-w-md w-full mx-4 shadow-2xl transform transition-all">
        <div class="flex justify-between items-center p-6 border-b border-gray-100">
            <h3 id="modalTitle" class="text-lg font-semibold text-gray-800">Detail Pajak Kendaraan</h3>
            <button id="modalCloseBtn" class="text-gray-400 hover:text-gray-600 text-2xl leading-none">&times;</button>
        </div>
        <div class="p-6 space-y-3">
            <p><strong>No. Polisi:</strong> <span id="modalNoPolisi"></span></p>
            <p><strong>Jenis:</strong> <span id="modalJenis"></span></p>
            <p><strong>Warna:</strong> <span id="modalWarna"></span></p>
            <p><strong>Jatuh Tempo:</strong> <span id="modalTanggalPajak"></span></p>
            <p><strong>Status:</strong> <span id="modalStatus" class="font-semibold"></span></p>
        </div>
        <div class="p-6 border-t border-gray-100">
            <a href="#" id="modalBayarBtn" class="block w-full text-center bg-primary text-white py-3 rounded-lg text-sm font-medium hover:bg-primary-dark transition-colors">
                Bayar Pajak
            </a>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Helper Functions
        function getLocalISODate(date) {
            const y = date.getFullYear();
            const m = String(date.getMonth() + 1).padStart(2, '0');
            const d = String(date.getDate()).padStart(2, '0');
            return `${y}-${m}-${d}`;
        }

        const today = new Date();
        today.setHours(0, 0, 0, 0);

        let currentDate = new Date(today.getFullYear(), today.getMonth(), 1);
        let selectedDate = null;
        let activeReminderPreviewDate = null;

        // Data from PHP
        const vehicles = <?php echo json_encode($vehicles ?? []); ?>;
        const reminders = <?php echo json_encode($reminders ?? []); ?>;
        let reminderEvents = [];

        const months = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];

        // DOM Elements
        const calendarGrid = document.getElementById('calendarGrid');
        const miniCalendarGrid = document.getElementById('miniCalendarGrid');
        const currentMonthYear = document.getElementById('currentMonthYear');
        const vehicleSelect = document.getElementById('vehicleSelect');
        const taxDueDateDisplay = document.getElementById('taxDueDateDisplay');
        const taxDueDateInput = document.getElementById('taxDueDate');
        const btnMotor = document.getElementById('btnMotor');
        const btnMobil = document.getElementById('btnMobil');
        const vehicleTypeInput = document.getElementById('vehicleTypeInput');
        const reminderDaysInput = document.getElementById('reminderDaysInput');
        const searchInput = document.getElementById('searchVehicle');
        const eventDetailModal = document.getElementById('eventDetailModal');
        const submitBtn = document.getElementById('submitReminder');

        function processReminders() {
            reminderEvents = [];
            reminders.forEach(r => {
                if (!r.tanggal || !r.reminder_type) return;
                const dueDate = new Date(r.tanggal);
                dueDate.setHours(0, 0, 0, 0);
                const reminderDate = new Date(dueDate);
                reminderDate.setDate(reminderDate.getDate() - parseInt(r.reminder_type, 10));
                reminderEvents.push({
                    date: getLocalISODate(reminderDate),
                    type: 'reminder',
                    vehicle: r.vehicle,
                    originalReminder: r
                });
            });
        }

        function updateReminderOptions(taxDateStr, vehicleId = null) {
            const reminderButtons = document.querySelectorAll('.reminder-btn');

            if (!taxDateStr) {
                reminderButtons.forEach(btn => {
                    btn.disabled = true;
                    btn.classList.remove('active');
                });
                reminderDaysInput.value = '';
                submitBtn.disabled = true;
                submitBtn.textContent = 'Pilih Kendaraan';
                return;
            }

            const taxDate = new Date(taxDateStr);
            taxDate.setHours(0, 0, 0, 0);
            const diffTime = taxDate.getTime() - today.getTime();
            const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

            let existingTypes = [];
            if (vehicleId) {
                existingTypes = reminders
                    .filter(r => r.vehicle_id == vehicleId)
                    .map(r => String(r.reminder_type));
            }

            let firstAvailable = null;

            reminderButtons.forEach(btn => {
                const days = parseInt(btn.dataset.days, 10);
                btn.classList.remove('active');

                const isAlreadySet = existingTypes.includes(String(days));

                if (diffDays < days || isAlreadySet) {
                    btn.disabled = true;
                    btn.title = isAlreadySet ? 'Pengingat ini sudah diatur' : 'Tanggal jatuh tempo terlalu dekat';
                } else {
                    btn.disabled = false;
                    btn.title = '';
                    if (!firstAvailable) firstAvailable = btn;
                }
            });

            if (firstAvailable) {
                firstAvailable.classList.add('active');
                reminderDaysInput.value = firstAvailable.dataset.days;
                submitBtn.disabled = false;
                submitBtn.textContent = 'Simpan Pengingat';
            } else {
                reminderDaysInput.value = '';
                submitBtn.disabled = true;
                submitBtn.textContent = 'Opsi pengingat tidak tersedia';
            }
        }

        function lockVehicleTypeButtons(activeType) {
            btnMotor.classList.remove('locked', 'active');
            btnMobil.classList.remove('locked', 'active');

            if (activeType === 'motor') {
                btnMotor.classList.add('active');
                btnMobil.classList.add('locked');
                vehicleTypeInput.value = 'motor';
            } else if (activeType === 'mobil') {
                btnMobil.classList.add('active');
                btnMotor.classList.add('locked');
                vehicleTypeInput.value = 'mobil';
            }
        }

        function resetVehicleTypeButtons() {
            btnMotor.classList.remove('active', 'locked');
            btnMobil.classList.remove('active', 'locked');
            vehicleTypeInput.value = '';
        }

        // Initialize form
        resetVehicleTypeButtons();
        updateReminderOptions(null);

        // Vehicle Select Change
        vehicleSelect.addEventListener('change', function() {
            const selectedOption = this.options[this.selectedIndex];
            activeReminderPreviewDate = null;

            if (selectedOption.value && selectedOption.dataset.taxDate) {
                taxDueDateInput.value = selectedOption.dataset.taxDate;

                const [y, m, d] = selectedOption.dataset.taxDate.split('-').map(Number);
                const dueDate = new Date(y, m - 1, d);

                taxDueDateDisplay.value = dueDate.toLocaleDateString('id-ID', {
                    day: 'numeric',
                    month: 'long',
                    year: 'numeric'
                });
                taxDueDateDisplay.style.color = '#374151';
                taxDueDateDisplay.style.backgroundColor = '#f9fafb';
                taxDueDateDisplay.style.borderColor = '#d1d5db';

                selectedDate = dueDate;
                selectedDate.setHours(0, 0, 0, 0);
                currentDate = new Date(y, m - 1, 1);

                const vehicleType = selectedOption.dataset.type;
                if (vehicleType) {
                    lockVehicleTypeButtons(vehicleType);
                }

                updateReminderOptions(selectedOption.dataset.taxDate, selectedOption.value);
            } else {
                taxDueDateInput.value = '';
                taxDueDateDisplay.value = '';
                taxDueDateDisplay.placeholder = 'Pilih kendaraan terlebih dahulu';
                taxDueDateDisplay.style.color = '#9ca3af';
                taxDueDateDisplay.style.backgroundColor = '#f3f4f6';
                taxDueDateDisplay.style.borderColor = '#e5e7eb';

                selectedDate = null;
                activeReminderPreviewDate = null;
                updateReminderOptions(null);
                resetVehicleTypeButtons();
            }

            updateMonthYear();
            renderCalendar();
            renderMiniCalendar();
        });

        // Toggle buttons
        btnMotor.addEventListener('click', function() {
            if (this.classList.contains('locked')) return;
            lockVehicleTypeButtons('motor');
        });

        btnMobil.addEventListener('click', function() {
            if (this.classList.contains('locked')) return;
            lockVehicleTypeButtons('mobil');
        });

        // Reminder Days Toggle
        document.querySelectorAll('.reminder-btn').forEach(btn => {
            btn.addEventListener('click', function() {
                if (this.disabled) return;
                document.querySelectorAll('.reminder-btn').forEach(b => b.classList.remove('active'));
                this.classList.add('active');
                reminderDaysInput.value = this.dataset.days;

                const dueDateStr = taxDueDateInput.value;
                if (dueDateStr) {
                    const dueDate = new Date(dueDateStr);
                    activeReminderPreviewDate = new Date(dueDate);
                    activeReminderPreviewDate.setDate(dueDate.getDate() - parseInt(this.dataset.days, 10));
                    activeReminderPreviewDate.setHours(0, 0, 0, 0);
                } else {
                    activeReminderPreviewDate = null;
                }
                renderMiniCalendar();
            });
        });

        // Calendar Navigation
        document.getElementById('prevMonth').addEventListener('click', () => {
            currentDate.setMonth(currentDate.getMonth() - 1);
            updateMonthYear();
            renderCalendar();
            renderMiniCalendar();
        });

        document.getElementById('nextMonth').addEventListener('click', () => {
            currentDate.setMonth(currentDate.getMonth() + 1);
            updateMonthYear();
            renderCalendar();
            renderMiniCalendar();
        });

        // Search
        searchInput.addEventListener('input', function() {
            const query = this.value.toLowerCase();
            document.querySelectorAll('.rm-event-block').forEach(block => {
                block.style.opacity = block.textContent.toLowerCase().includes(query) ? '1' : '0.3';
            });
        });

        // Cancel Button
        document.getElementById('btnCancel').addEventListener('click', function() {
            vehicleSelect.value = '';
            document.getElementById('reminderForm').reset();
            selectedDate = null;
            activeReminderPreviewDate = null;

            taxDueDateInput.value = '';
            taxDueDateDisplay.value = '';
            taxDueDateDisplay.placeholder = 'Pilih kendaraan terlebih dahulu';
            taxDueDateDisplay.style.color = '#9ca3af';
            taxDueDateDisplay.style.backgroundColor = '#f3f4f6';
            taxDueDateDisplay.style.borderColor = '#e5e7eb';

            resetVehicleTypeButtons();
            updateReminderOptions(null);
            currentDate = new Date(today.getFullYear(), today.getMonth(), 1);

            updateMonthYear();
            renderCalendar();
            renderMiniCalendar();
        });

        // Add Button
        document.getElementById('btnAddReminder').addEventListener('click', function() {
            vehicleSelect.focus();
        });

        // Form Validation
        document.getElementById('reminderForm').addEventListener('submit', function(e) {
            if (!vehicleSelect.value) {
                e.preventDefault();
                alert('Silakan pilih kendaraan terlebih dahulu.');
                vehicleSelect.focus();
            }
        });

        // Calendar Functions
        function renderCalendar() {
            const year = currentDate.getFullYear();
            const month = currentDate.getMonth();
            const firstDay = new Date(year, month, 1).getDay();
            const daysInMonth = new Date(year, month + 1, 0).getDate();
            const daysInPrevMonth = new Date(year, month, 0).getDate();

            let html = '';

            for (let i = firstDay - 1; i >= 0; i--) {
                const day = daysInPrevMonth - i;
                const date = new Date(year, month - 1, day);
                html += generateCalendarCell(date, day, true);
            }

            for (let day = 1; day <= daysInMonth; day++) {
                const date = new Date(year, month, day);
                html += generateCalendarCell(date, day, false);
            }

            const totalCells = firstDay + daysInMonth;
            const remainingCells = totalCells % 7 === 0 ? 0 : 7 - (totalCells % 7);

            for (let day = 1; day <= remainingCells; day++) {
                const date = new Date(year, month + 1, day);
                html += generateCalendarCell(date, day, true);
            }

            calendarGrid.innerHTML = html;
        }

        function generateCalendarCell(date, day, isMuted) {
            const dateStr = getLocalISODate(date);
            const dateTime = date.getTime();
            const isToday = dateTime === today.getTime();
            const isSelected = selectedDate && dateTime === selectedDate.getTime();

            const dueEventsOnDate = reminders.filter(r => r.tanggal?.substring(0, 10) === dateStr);
            const uniqueDueEvents = [];
            const seenVehicles = new Set();
            dueEventsOnDate.forEach(event => {
                if (!seenVehicles.has(event.vehicle_id)) {
                    seenVehicles.add(event.vehicle_id);
                    uniqueDueEvents.push(event);
                }
            });

            const hasDueEvent = uniqueDueEvents.length > 0;
            const reminderEventsOnDate = reminderEvents.filter(e => e.date === dateStr && e.type === 'reminder');
            const hasReminderEvent = reminderEventsOnDate.length > 0;
            const isOverdue = hasDueEvent && dateTime < today.getTime();

            let cellClass = 'rm-cal-cell';
            if (isToday) cellClass += ' today';
            if (isSelected) cellClass += ' selected';
            if (hasDueEvent) cellClass += ' has-event';

            let html = `<div class="${cellClass}" data-date="${dateStr}">`;
            html += '<div class="rm-date-top">';

            if (hasDueEvent && !isMuted) {
                html += '<div class="rm-event-dot" title="Jatuh Tempo"></div>';
            }
            if (hasReminderEvent && !isMuted) {
                html += '<div class="rm-event-dot reminder-dot" title="Pengingat Aktif"></div>';
            }

            html += `<div class="rm-date-num${isMuted ? ' muted' : ''}">${day}</div>`;
            html += '</div>';

            if (hasDueEvent && !isMuted) {
                uniqueDueEvents.forEach(event => {
                    const overdueClass = isOverdue ? ' overdue' : '';
                    const noPolisi = event.vehicle?.no_polisi || event.no_polisi || 'Kendaraan';
                    const jenis = event.vehicle?.jenis || event.jenis || '';
                    html += `<div class="rm-event-block${overdueClass}" data-vehicle-id="${event.vehicle_id}" title="Klik untuk detail">`;
                    html += `Pajak ${jenis}<br>(${noPolisi})`;
                    html += '</div>';
                });
            }

            html += '</div>';
            return html;
        }

        function renderMiniCalendar() {
            const year = currentDate.getFullYear();
            const month = currentDate.getMonth();
            const days = ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'];
            let html = '';

            days.forEach(day => html += `<div class="rm-mini-day">${day}</div>`);

            const firstDay = new Date(year, month, 1).getDay();
            const daysInMonth = new Date(year, month + 1, 0).getDate();
            const daysInPrevMonth = new Date(year, month, 0).getDate();

            for (let i = firstDay - 1; i >= 0; i--) {
                html += `<div class="rm-mini-date muted">${daysInPrevMonth - i}</div>`;
            }

            for (let day = 1; day <= daysInMonth; day++) {
                const date = new Date(year, month, day);
                const dateStr = getLocalISODate(date);
                const dateTime = date.getTime();
                const isToday = dateTime === today.getTime();
                const isSelected = selectedDate && dateTime === selectedDate.getTime();
                const isPreview = activeReminderPreviewDate && dateTime === activeReminderPreviewDate.getTime();
                const hasDueEvent = reminders.some(r => r.tanggal?.substring(0, 10) === dateStr);
                const hasReminderEvent = reminderEvents.some(e => e.date === dateStr && e.type === 'reminder');

                let dateClass = 'rm-mini-date';
                if (isSelected) dateClass += ' due-date-full';
                else if (isPreview) dateClass += ' preview-outline';
                else if (isToday) dateClass += ' today-subtle';
                else if (hasDueEvent || hasReminderEvent) dateClass += ' has-event';

                html += `<div class="${dateClass}">${day}</div>`;
            }

            const totalCells = firstDay + daysInMonth;
            const remainingCells = totalCells % 7 === 0 ? 0 : 7 - (totalCells % 7);

            for (let day = 1; day <= remainingCells; day++) {
                html += `<div class="rm-mini-date muted">${day}</div>`;
            }

            miniCalendarGrid.innerHTML = html;
        }

        function updateMonthYear() {
            currentMonthYear.textContent = `${months[currentDate.getMonth()]} ${currentDate.getFullYear()}`;
        }

        // Modal Handling
        calendarGrid.addEventListener('click', function(e) {
            const eventBlock = e.target.closest('.rm-event-block');
            if (eventBlock && eventBlock.dataset.vehicleId) {
                const vehicleId = parseInt(eventBlock.dataset.vehicleId, 10);
                const reminder = reminders.find(r => r.vehicle_id === vehicleId);

                if (reminder && reminder.vehicle) {
                    const vehicle = reminder.vehicle;
                    const dueDate = new Date(vehicle.tanggal_pajak);
                    const isOverdue = dueDate.getTime() < today.getTime();

                    document.getElementById('modalNoPolisi').textContent = vehicle.no_polisi;
                    document.getElementById('modalJenis').textContent = vehicle.jenis.charAt(0).toUpperCase() + vehicle.jenis.slice(1);
                    document.getElementById('modalWarna').textContent = vehicle.warna;
                    document.getElementById('modalTanggalPajak').textContent = dueDate.toLocaleDateString('id-ID', {
                        day: 'numeric',
                        month: 'long',
                        year: 'numeric'
                    });

                    const statusSpan = document.getElementById('modalStatus');
                    statusSpan.textContent = isOverdue ? 'Jatuh Tempo' : 'Aktif';
                    statusSpan.style.color = isOverdue ? '#ef4444' : '#10b981';

                    document.getElementById('modalBayarBtn').href = `/pembayaran/${vehicle.id}`;
                    eventDetailModal.style.display = 'flex';
                }
            }
        });

        document.getElementById('modalCloseBtn').addEventListener('click', () => {
            eventDetailModal.style.display = 'none';
        });

        eventDetailModal.addEventListener('click', function(e) {
            if (e.target === this) {
                eventDetailModal.style.display = 'none';
            }
        });

        // Initial Render
        processReminders();
        renderCalendar();
        renderMiniCalendar();
        updateMonthYear();
    });

    // Notification Dropdown
    function toggleNotificationDropdown() {
        const dropdown = document.getElementById('notificationDropdown');
        dropdown.classList.toggle('hidden');
    }

    // Tutup dropdown saat klik di luar
    document.addEventListener('click', function(event) {
        const dropdown = document.getElementById('notificationDropdown');
        const bell = event.target.closest('[onclick="toggleNotificationDropdown()"]');

        if (!bell && dropdown && !dropdown.classList.contains('hidden')) {
            dropdown.classList.add('hidden');
        }
    });

    // Tandai semua sudah dibaca
    function markAllAsRead(event) {
        event.stopPropagation();

        // Hapus class unread dan dot
        const unreadItems = document.querySelectorAll('.dropdown-notif-item.unread');
        unreadItems.forEach(item => {
            item.classList.remove('unread');
            const dot = item.querySelector('.dropdown-notif-dot');
            if (dot) dot.remove();
        });

        // Hapus red dot di bell icon
        const bellDot = document.querySelector('.bell-dot, .bg-red-500.rounded-full');
        if (bellDot) bellDot.style.display = 'none';

        // Optional: Kirim request ke server
        // fetch('/notifications/mark-all-read', { method: 'POST' });
    }
</script>

<?php include 'includes/footer.php'; ?>