<?php
// reminder.php
require_once 'config.php';

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'add_reminder') {
    $vehicle_id = $_POST['vehicle_id'] ?? '';
    $tanggal = $_POST['tanggal'] ?? '';
    $reminder_type = $_POST['reminder_type'] ?? '';
    $vehicle_type = $_POST['vehicle_type'] ?? '';

    // Validation
    $errors = [];
    if (empty($vehicle_id)) $errors[] = 'Pilih kendaraan terlebih dahulu.';
    if (empty($tanggal)) $errors[] = 'Tanggal jatuh tempo harus diisi.';
    if (empty($reminder_type)) $errors[] = 'Pilih jenis pengingat.';

    if (empty($errors)) {
        // Here you would insert into database
        // For now, just add to sample data
        $newReminder = [
            'id' => count($reminders) + 1,
            'vehicle_id' => (int)$vehicle_id,
            'tanggal' => $tanggal,
            'reminder_type' => $reminder_type,
            'vehicle' => array_filter($vehicles, function ($v) use ($vehicle_id) {
                return $v['id'] == $vehicle_id;
            })[0] ?? null
        ];
        $reminders[] = $newReminder;
        $_SESSION['success'] = 'Pengingat berhasil disimpan!';

        // Redirect to prevent form resubmission
        header('Location: reminder.php');
        exit;
    } else {
        $_SESSION['errors'] = $errors;
    }
}

$success = $_SESSION['success'] ?? null;
$errors = $_SESSION['errors'] ?? [];
unset($_SESSION['success'], $_SESSION['errors']);

$pageTitle = 'Pengingat';
include 'includes/header.php';
?>

<!-- Main Content -->
<main class="pt-24 pb-12 bg-gray-50">
    <div class="max-w-7xl mx-auto pt-10">
        <div class="flex flex-col lg:flex-row gap-8">

            <!-- LEFT SIDE - CALENDAR -->
            <div class="flex-1">
                <!-- Month Header -->
                <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8 p-4">
                    <div class="flex items-center gap-4">
                        <button id="prevMonth" class="w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center hover:bg-primary-dark transition-colors">
                            <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                <path d="M15 18l-6-6 6-6"></path>
                            </svg>
                        </button>
                        <h2 id="currentMonthYear" class="text-xl font-bold text-gray-800 min-w-[200px] text-center"></h2>
                        <button id="nextMonth" class="w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center hover:bg-primary-dark transition-colors">
                            <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                <path d="M9 18l6-6-6-6"></path>
                            </svg>
                        </button>
                    </div>

                    <div class="relative w-full sm:w-80">
                        <svg class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                            <circle cx="11" cy="11" r="8"></circle>
                            <path d="M21 21l-4.35-4.35"></path>
                        </svg>
                        <input
                            type="text"
                            placeholder="Cari kendaraan..."
                            id="searchVehicle"
                            class="w-full pl-10 pr-4 py-2.5 rounded-lg border border-gray-200 bg-gray-50 text-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary" />
                    </div>
                </div>

                <!-- Calendar Card -->
                <div class="bg-white rounded-2xl border border-gray-100 overflow-hidden shadow-sm">
                    <!-- Calendar Header -->
                    <div class="grid grid-cols-7 bg-gray-50/80 border-b border-gray-100">
                        <?php foreach (['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'] as $day): ?>
                            <div class="py-3 text-center text-sm font-semibold text-gray-600 border-r border-gray-100 last:border-r-0">
                                <?php echo $day; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <!-- Calendar Grid -->
                    <div id="calendarGrid" class="grid grid-cols-7">
                        <!-- Generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- RIGHT SIDE - FORM -->
            <div class="w-full lg:w-[380px] flex-shrink-0">
                <div class="px-4 pt-4">

                    <!-- Alert Messages -->
                    <?php if ($success): ?>
                        <div class="mb-4 p-3 bg-green-50 border border-green-200 rounded-lg text-green-700 text-sm animate-fadeIn">
                            <?php echo htmlspecialchars($success); ?>
                        </div>
                    <?php endif; ?>

                    <?php if (!empty($errors)): ?>
                        <div class="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm animate-fadeIn">
                            <?php foreach ($errors as $error): ?>
                                <p><?php echo htmlspecialchars($error); ?></p>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>

                    <!-- Action Buttons -->
                    <div class="flex gap-3 mb-6">
                        <button id="btnAddReminder" class="flex-1 bg-primary text-white py-2.5 px-4 rounded-lg text-sm font-medium hover:bg-primary-dark active:scale-95 transition-all">
                            + Tambah
                        </button>
                        <button id="btnCancel" class="flex-1 bg-purple-50 text-primary py-2.5 px-4 rounded-lg text-sm font-medium hover:bg-purple-100 active:scale-95 transition-all flex items-center justify-center gap-1.5">
                            <svg width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                <path d="M18 6L6 18M6 6l12 12"></path>
                            </svg>
                            Batalkan
                        </button>
                    </div>

                    <!-- Form -->
                    <form id="reminderForm" action="reminder.php" method="POST">
                        <input type="hidden" name="action" value="add_reminder">

                        <!-- Vehicle Selection -->
                        <div class="mb-3">
                            <label class="block text-sm font-medium text-gray-700 mb-2">Kendaraan</label>
                            <div class="relative">
                                <select
                                    id="vehicleSelect"
                                    name="vehicle_id"
                                    class="w-full appearance-none px-4 py-3 rounded-lg border border-gray-200 text-sm text-gray-600 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary cursor-pointer"
                                    required>
                                    <option value="">Pilih kendaraan</option>
                                    <?php foreach ($vehicles as $vehicle): ?>
                                        <option
                                            value="<?php echo $vehicle['id']; ?>"
                                            data-plate="<?php echo htmlspecialchars($vehicle['no_polisi']); ?>"
                                            data-type="<?php echo $vehicle['jenis']; ?>"
                                            data-tax-date="<?php echo $vehicle['tanggal_pajak']; ?>">
                                            <?php echo htmlspecialchars($vehicle['no_polisi']); ?> (<?php echo ucfirst($vehicle['jenis']); ?>)
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                                <svg class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                    <path d="M6 9l6 6 6-6"></path>
                                </svg>
                            </div>
                            <?php if (empty($vehicles)): ?>
                                <p class="text-xs text-amber-600 mt-2">Silakan cek pajak dengan NIK terlebih dahulu di halaman Cek Pajak.</p>
                            <?php endif; ?>
                        </div>

                        <!-- Vehicle Type -->
                        <div class="mb-3">
                            <label class="block text-sm font-medium text-gray-700 mb-2">
                                Tipe Kendaraan
                            </label>
                            <div id="vehicleTypeToggle" class="flex gap-2">
                                <button
                                    type="button"
                                    id="btnMotor"
                                    data-type="motor"
                                    class="toggle-btn flex-1 flex items-center justify-center gap-2 py-2.5 px-3 rounded-lg border-2 text-sm font-medium transition-all"
                                    disabled>
                                    <svg width="20" height="20" viewBox="0 0 50 50" fill="currentColor">
                                        <path d="M34.1 12.4c-1.1-.6-2.4-.9-3.8-.9H19.7c-1.4 0-2.7.3-3.8.9L10 16v12.1c0 1.7 1.4 3.1 3.1 3.1h1.5c1.7 0 3.1-1.4 3.1-3.1V28h14.6v.1c0 1.7 1.4 3.1 3.1 3.1h1.5c1.7 0 3.1-1.4 3.1-3.1V16l-5.9-3.6zM20 20.5c-.8 0-1.5-.7-1.5-1.5s.7-1.5 1.5-1.5 1.5.7 1.5 1.5-.7 1.5-1.5 1.5zm10 0c-.8 0-1.5-.7-1.5-1.5s.7-1.5 1.5-1.5 1.5.7 1.5 1.5-.7 1.5-1.5 1.5z" />
                                    </svg>
                                    Motor
                                </button>
                                <button
                                    type="button"
                                    id="btnMobil"
                                    data-type="mobil"
                                    class="toggle-btn flex-1 flex items-center justify-center gap-2 py-2.5 px-3 rounded-lg border-2 text-sm font-medium transition-all"
                                    disabled>
                                    <svg width="20" height="20" viewBox="0 0 50 50" fill="currentColor">
                                        <path d="M38.5 17.5l-3.2-6.4c-.5-1-1.5-1.6-2.6-1.6H17.3c-1.1 0-2.1.6-2.6 1.6l-3.2 6.4c-2 .6-3.5 2.4-3.5 4.6v7.4c0 1.4 1.1 2.5 2.5 2.5h1.5c1.4 0 2.5-1.1 2.5-2.5v-1.5h15v1.5c0 1.4 1.1 2.5 2.5 2.5h1.5c1.4 0 2.5-1.1 2.5-2.5V22.1c0-2.2-1.5-4-3.5-4.6zM15 24c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm20 0c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z" />
                                    </svg>
                                    Mobil
                                </button>
                            </div>
                            <input type="hidden" name="vehicle_type" id="vehicleTypeInput" value="">
                        </div>

                        <!-- Tax Due Date -->
                        <div class="mb-3">
                            <label class="block text-sm font-medium text-gray-700 mb-2">Tanggal Jatuh Tempo Pajak</label>
                            <div class="relative">
                                <input
                                    type="text"
                                    id="taxDueDateDisplay"
                                    disabled
                                    readonly
                                    placeholder="Pilih kendaraan terlebih dahulu"
                                    class="w-full px-4 py-3 rounded-lg border border-gray-200 bg-gray-100 text-gray-400 text-sm cursor-not-allowed" />
                                <input type="hidden" name="tanggal" id="taxDueDate" value="">
                                <div class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400/30">
                                    <svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                                        <path d="M16 2v4M8 2v4M3 10h18"></path>
                                    </svg>
                                </div>
                            </div>
                        </div>

                        <!-- Reminder Before Due Date -->
                        <div class="mb-3">
                            <label class="block text-sm font-medium text-gray-700 mb-2">Pengingat Sebelum Jatuh Tempo</label>
                            <div id="reminderDaysToggle" class="flex gap-2">
                                <button type="button" data-days="3" class="reminder-btn flex-1 py-2 px-3 rounded-lg border-2 text-sm font-medium transition-all" disabled>
                                    3 Hari
                                </button>
                                <button type="button" data-days="7" class="reminder-btn flex-1 py-2 px-3 rounded-lg border-2 text-sm font-medium transition-all" disabled>
                                    7 Hari
                                </button>
                                <button type="button" data-days="30" class="reminder-btn flex-1 py-2 px-3 rounded-lg border-2 text-sm font-medium transition-all" disabled>
                                    30 Hari
                                </button>
                            </div>
                            <input type="hidden" name="reminder_type" id="reminderDaysInput" value="">
                        </div>

                        <!-- Mini Calendar -->
                        <div class="mb-5 bg-gray-100 rounded-xl p-3">
                            <div id="miniCalendarGrid" class="grid grid-cols-7 gap-y-1.5 text-center">
                                <!-- Generated by JavaScript -->
                            </div>
                        </div>

                        <!-- Submit Button -->
                        <button type="submit" id="submitReminder" class="w-full bg-primary text-white py-3.5 rounded-lg text-sm font-medium hover:bg-primary-dark active:scale-95 transition-all disabled:opacity-50 disabled:cursor-not-allowed" disabled>
                            Pilih Kendaraan
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

<!-- Event Detail Modal -->
<div id="eventDetailModal" class="fixed inset-0 bg-black/50 z-50 hidden items-center justify-center">
    <div class="bg-white rounded-2xl max-w-md w-full mx-4 shadow-2xl transform transition-all">
        <div class="flex justify-between items-center p-6 border-b border-gray-100">
            <h3 id="modalTitle" class="text-lg font-semibold text-gray-800">Detail Pajak Kendaraan</h3>
            <button id="modalCloseBtn" class="text-gray-400 hover:text-gray-600 text-2xl leading-none">&times;</button>
        </div>
        <div class="p-6 space-y-3">
            <p><strong>No. Polisi:</strong> <span id="modalNoPolisi"></span></p>
            <p><strong>Jenis:</strong> <span id="modalJenis"></span></p>
            <p><strong>Warna:</strong> <span id="modalWarna"></span></p>
            <p><strong>Jatuh Tempo:</strong> <span id="modalTanggalPajak"></span></p>
            <p><strong>Status:</strong> <span id="modalStatus" class="font-semibold"></span></p>
        </div>
        <div class="p-6 border-t border-gray-100">
            <a href="#" id="modalBayarBtn" class="block w-full text-center bg-primary text-white py-3 rounded-lg text-sm font-medium hover:bg-primary-dark transition-colors">
                Bayar Pajak
            </a>
        </div>
    </div>
</div>

<?php include 'includes/footer.php'; ?>